name: dcase2024
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - audioread=3.0.1=py38h578d9bd_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.0.9=py38hfa26641_8
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_hceff1ee_706
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h2019614_0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.2=py38heeb90bb_0
  - graphite2=1.3.14=h5888daf_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.23.1=h84d6215_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h3d81e11_1002
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=h99ab3db_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libprotobuf=5.29.3=h501fc15_1
  - librosa=0.10.2.post1=pyhd8ed1ab_0
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libudev1=257.7=hbe16f8c_0
  - libunwind=1.8.2=h1441ba7_0
  - liburing=2.11=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.11.8=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.41.1=py38h94a1851_0
  - lz4-c=1.10.0=h5888daf_1
  - mad=0.15.1b=h9c3ff4c_1
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py38h06a4308_0
  - msgpack-python=1.0.8=py38hea7755e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py38h06a4308_0
  - ninja=1.13.1=h171cf75_0
  - numba=0.58.1=py38h4144172_0
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38h01efb38_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pillow=10.4.0=py38h2bc05a7_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytorch=2.4.1=py3.8_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-lightning=1.9.4=pyhd8ed1ab_1
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h59b608b_3
  - sdl2=2.32.54=h3f2d84a_0
  - sdl3=3.2.18=h68140b3_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h8bd8927_1
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py38h7f0c24c_0
  - sqlite=3.45.2=h2c6b66d_0
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.13.3=py38h06a4308_0
  - tbb=2022.1.0=h4ce085d_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.4.1=py38_cu124
  - torchmetrics=1.5.2=pyhe5570ce_0
  - torchtriton=3.0.0=py38
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py38h01eb140_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - youtube-dl=2021.12.17=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - arrow==1.3.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - black==19.10b0
      - cachetools==5.5.2
      - cfgv==3.4.0
      - click==8.1.8
      - codecarbon==2.3.4
      - cython==3.1.2
      - dcase-util==0.2.20
      - desed==1.3.8
      - distlib==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - identify==2.6.1
      - iniconfig==2.1.0
      - intervaltree==3.1.0
      - jams==0.3.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - lazy-dataset==0.0.15
      - markdown==3.7
      - markupsafe==2.1.5
      - mir-eval==0.8.2
      - multidict==6.1.0
      - mutagen==1.47.0
      - nodeenv==1.9.1
      - oauthlib==3.3.1
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.5.0
      - pre-commit==3.5.0
      - prometheus-client==0.21.1
      - propcache==0.2.0
      - protobuf==5.29.5
      - psds-eval==0.5.3
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycodestyle==2.5.0
      - pycryptodomex==3.23.0
      - pydot-ng==2.0.0
      - pyloudnorm==0.1.1
      - pynvml==11.5.3
      - pytest==8.3.5
      - python-magic==0.4.27
      - rapidfuzz==3.9.7
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scaper==1.6.5
      - sed-eval==0.2.1
      - sed-scores-eval==0.0.4
      - sortedcontainers==2.4.0
      - sox==1.4.0
      - soxbindings==1.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - toml==0.10.2
      - tomli==2.2.1
      - typed-ast==1.5.5
      - types-python-dateutil==2.9.0.20241206
      - validators==0.34.0
      - virtualenv==20.31.2
      - websockets==13.1
      - werkzeug==3.0.6
      - yarl==1.15.2
      - yt-dlp==2024.10.22
prefix: /root/miniconda3/envs/dcase2024
